# Generated by Django 5.0.1 on 2024-01-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200, verbose_name='Titulo')),
                ('subtitle', models.TextField(max_length=200, verbose_name='Subtitulo')),
                ('content', models.TextField(verbose_name='Descripción')),
                ('link', models.URLField(verbose_name='Link referencia')),
                ('image', models.ImageField(upload_to='services', verbose_name='Imagen')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
        ),
    ]
